import { MetadataRoute } from "next";

const blockedUserAgents = [
  '.ai',
  'Agentic',
  'AI Article Writer',
  'AI Chat',
  'AI Content Detector',
  'AI Dungeon',
  'AI Search',
  'AI SEO Crawler',
  'AI Writer',
  'ai-proxy',
  'AI21 Labs',
  'AI2Bot',
  'AIBot',
  'aiHitBot',
  'AIMatrix',
  'AISearchBot',
  'AI Training',
  'AITraining',
  'Alexa',
  'Alpha AI',
  'AlphaAI',
  'Amazon Bedrock',
  'Amazon-Kendra',
  'Amazon Lex',
  'Amazon Comprehend',
  'Amazon Sagemaker',
  'Amazon Silk',
  'Amazon Textract',
  'AmazonBot',
  'Amelia',
  'AndersPinkBot',
  'AndiBot',
  'Anthropic',
  'AnyPicker',
  'Anyword',
  'Applebot',
  'Aria Browse',
  'Articoolo',
  'AutoGLM',
  'Automated Writer',
  'AutoML',
  'AwarioRssBot',
  'AwarioSmartBot',
  'Azure',
  'BabyAGI',
  'BardBot',
  'Brave Leo',
  'Brightbot',
  'ByteDance',
  'Bytespider',
  'CatBoost',
  'CC-Crawler',
  'CCBot',
  'chatbot',
  'ChatGLM',
  'ChatGPT-User',
  'Chinchilla',
  'Claude',
  'ClearScope',
  'Cohere',
  'Common Crawl',
  'CommonCrawl',
  'Content Harmony',
  'Content King',
  'Content Optimizer',
  'Content Samurai',
  'ContentAtScale',
  'ContentBot',
  'Contentedge',
  'Conversion AI',
  'Copilot',
  'CopyAI',
  'Copymatic',
  'Copyscape',
  'Cotoyogi',
  'CrawlQ AI',
  'Crawlspace',
  'Crew AI',
  'CrewAI',
  'DALL-E',
  'DataForSeoBot',
  'DataProvider',
  'DeepAI',
  'DeepL',
  'DeepMind',
  'DeepSeek',
  'Diffbot',
  'Doubao AI',
  'DuckAssistBot',
  'FacebookBot',
  'FacebookExternalHit',
  'Factset',
  'Falcon',
  'Firecrawl',
  'Flyriver',
  'Frase AI',
  'FriendlyCrawler',
  'Gemini',
  'Gemma',
  'GenAI',
  'Genspark',
  'GLM',
  'Goose',
  'GPT',
  'GPTBot',
  'Grammarly',
  'Grendizer',
  'Grok',
  'GT Bot',
  'GTBot',
  'Hemingway Editor',
  'Hugging Face',
  'Hypotenuse AI',
  'iaskspider',
  'ICC-Crawler',
  'ImageGen',
  'ImagesiftBot',
  'img2dataset',
  'imgproxy',
  'INK Editor',
  'INKforall',
  'IntelliSeek',
  'Inferkit',
  'ISSCyberRiskCrawler',
  'JasperAI',
  'Kafkai',
  'Kangaroo',
  'Keyword Density AI',
  'Knowledge',
  'KomoBot',
  'Lensa',
  'Lightpanda',
  'LLaMA',
  'LLMs',
  'magpie-crawler',
  'Manus',
  'MarketMuse',
  'Meltwater',
  'Meta AI',
  'Meta-AI',
  'Meta-External',
  'MetaAI',
  'MetaTagBot',
  'Mistral',
  'Monica',
  'Narrative',
  'NeevaBot',
  'Neural Text',
  'NeuralSEO',
  'Nova Act',
  'NovaAct',
  'OAI-SearchBot',
  'Omgili',
  'Open AI',
  'OpenAI',
  'OpenBot',
  'OpenText AI',
  'Operator',
  'Outwrite',
  'Page Analyzer AI',
  'PanguBot',
  'Paperlibot',
  'Paraphraser.io',
  'Perplexity',
  'PetalBot',
  'Phind',
  'PiplBot',
  'ProWritingAid',
  'Puppeteer',
  'Qualified',
  'QuillBot',
  'Qwen',
  'RobotSpider',
  'Rytr',
  'SaplingAI',
  'Scalenut',
  'Scraper',
  'Scrapy',
  'ScriptBook',
  'SEO Content Machine',
  'SEO Robot',
  'SemrushBot',
  'Sentibot',
  'Sidetrade',
  'Simplified AI',
  'Sitefinity',
  'Skydancer',
  'SlickWrite',
  'Sonic',
  'Spin Rewriter',
  'Spinbot',
  'Stability',
  'StableDiffusionBot',
  'Sudowrite',
  'Super Agent',
  'Surfer AI',
  'Text Blaze',
  'TextCortex',
  'The Knowledge AI',
  'TikTokSpider',
  'Timpibot',
  'Traefik',
  'VelenPublicWebCrawler',
  'Vidnami AI',
  'Webzio',
  'Whisper',
  'WordAI',
  'Wordtune',
  'WormsGTP',
  'WPBot',
  'Writecream',
  'WriterZen',
  'Writescope',
  'Writesonic',
  'xAI',
  'xBot',
  'YaML',
  'YouBot',
  'Zero GTP',
  'Zerochat',
  'Zhipu',
  'Zimm'
];

export default function robots(): MetadataRoute.Robots {
    return {
        rules: [
            {
                userAgent: blockedUserAgents,
                disallow: "/",
            },
            {
                userAgent: "*",
                allow: "/",
                crawlDelay: 10,
            },
        ],
        sitemap: `${process.env.NEXT_PUBLIC_BASE_URL}/sitemap.xml`,
    }
}